# Site settings
title: Rob King - Jack of All Native Mobile Development
email: rob@robking.me
description: # this means to ignore newlines until "baseurl:"
  My name is Rob King, and I am proficient in Android, iOS, Windows 8.1, and motorcycles.
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robking.me" # the base hostname & protocol for your site
twitter_username: robtylerking
github_username:  RobTKing
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default Settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Rob King
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
